### ISSUE TITLE
你好，非队列的rpc 处理能否放入独立的goroutine？

### ISSUE THREAD

**Issue by ybm2dyd** [davyxu/cellnet#106]
比如我想编写一个无状态服务器（dbproxy、sdkproxy这种）

gameserver是单线程带queue的异步rpc调用，dbproxy那边需要每个请求都在独立的goroutine处理阻塞的DB操作逻辑（redis、mongo）

现有实现，如果没有队列，是在连接的session的读线程处理，无法实现并发。

// 有队列时队列调用，无队列时直接调用
func QueuedCall(queue EventQueue, callback func(), isMulti bool) {
	if queue == nil {
		if isMulti {
			go callback()
		} else {
			callback()
		}
	} else {
		queue.Post(callback)
	}
}

**Comment by ybm2dyd** [comment]
1

**Comment by davyxu** [comment]
1. 不要再用dbproxy这种设计, 10年前的东西, 一崩全崩
2. 单线程阻塞就开多进程,  不喜欢阻塞就单线程非阻塞异步

**Comment by scrong1** [comment]
你队列响应这个消息的时候，go func一下不就不阻塞，且到其他协程去等待了吗

**Comment by scrong1** [comment]
你响应这个消息的handle函数里面，go func一下不就不阻塞，且到其他协程去等待了吗
