### ISSUE TITLE
为啥不用io.ReadAtLeast ,这样不会粘包么

### ISSUE THREAD

**Issue by Anehta** [davyxu/cellnet#11]
pktstream.go里
Read函数部分
直接readFull有点不靠谱吧,这样封包没发全会直接断开的吧,tcp搞的和udp一样一个包一个包发有什么特殊含义么。
主要我用websocket发送消息的时候,send我不知道是不是writeFull....内部实现又看不到。
用ReadAtLeast不就没啥问题了么。

**Comment by Anehta** [comment]
我看了下websocket的RFC标准，标准倒是规定每次send必须是合包完成了。
但是事实上我觉得每个引擎标准实现的不一样,说不定还是会有这种问题。

**Comment by davyxu** [comment]
readFull的意思是, 读取指定长度. 就是典型的处理粘包问题
websocket貌似也有类似的机制.

**Comment by Anehta** [comment]
窝草。没看清楚前面有个make,果然凌晨写代码意识模糊了。
