### ISSUE TITLE
可否支持websocket？

### ISSUE THREAD

**Issue by moketao** [davyxu/cellnet#14]
如题，可否支持websocket

**Comment by davyxu** [comment]
pull req里有人推过.   websocket可以用第三方库, 没必要使用cellnet多重封装

**Comment by moketao** [comment]
我最近的项目都是h5，都需要websocket，我想这必定是一个趋势。建议还是把websocket直接整合进来，开箱即用。
当然，如果不方便，可否给出一个封装的指导文章呢，我想我要的有点多了，抱歉。。。囧

**Comment by davyxu** [comment]
没必要封装, 很多websocket库开箱就可以用
https://github.com/gorilla/websocket

**Comment by moketao** [comment]
不好意思，之前没注意有这个 pull req ：
https://github.com/davyxu/cellnet/pull/9
代码量说少也不少了，我先看看，谢谢。
