### ISSUE TITLE
建议工程的描述加上 server framework关键字

### ISSUE THREAD

**Issue by luochuanyuewu** [davyxu/cellnet#17]
因为这几天在不断搜索golang相关的游戏服务器技术，但却很难搜到cellnet，是因为一般人都是搜的 game, server framework这几个关键字。。而出来的都是些几百k的项目。 很少有人会去搜索 network library吧~ 所以只是个建议，让更多人发现cellnet.

**Comment by davyxu** [comment]
感谢对cellnet的支持

cellnet定位不是framework.  cellorigin项目偏向于framework甚至于成熟的起始工程

可以关注我的github, 这样就更容易找到

**Comment by luochuanyuewu** [comment]
已关注。
