### ISSUE TITLE
BroadcastToClientList 有一个小BUG

### ISSUE THREAD

**Issue by lantiao** [davyxu/cellnet#2]
不是大问题，只是新创建空间后，地址没有赋给self对象造成的。
表现 BroadcastToClientList 指定用户不能正常收到广播。

review源码中发现问题出在：
router\routerconn.go 187行，

把
list = make([]int64, 0)
改成
self[routerSes] = make([]int64, 0)
list = self[routerSes]

 @davyxu

**Comment by davyxu** [comment]
ok, thanks

**Comment by lantiao** [comment]
thinks.
