### ISSUE TITLE
能否建一个讨论QQ群，方便大家讨论。

### ISSUE THREAD

**Issue by Vigour1989** [davyxu/cellnet#20]

**Comment by davyxu** [comment]
309800774这是我博客的讨论群，主要讨论服务器技术，不限语言和其他主题，不是闲聊群
至于是否需要专门建立cellnet或者我的github讨论群征集大家意见

建议本issue不要关闭

**Comment by korman** [comment]
我觉得也是需要

**Comment by bwangel23** [comment]
建个Google讨论组的邮件列表吧，我加过的大部分QQ群都成了灌水群。

感觉邮件列表因为要发邮件，大家发之前都会认真组织一下语言。

**Comment by davyxu** [comment]
这是我的博客技术群309800774，无水纯技术，感兴趣可以加
