### ISSUE TITLE
不用go的socket客户端没有例子，是不是不支持？

### ISSUE THREAD

**Issue by ihxzihxz** [davyxu/cellnet#23]
不用go的socket客户端没有例子，是不是不支持？能用纯socket给一个例子吗？

**Comment by davyxu** [comment]
什么客户端？

**Comment by bwangel23** [comment]
弱弱的插个楼，可以和Java客户端通信吗？

我们目前想做一个APP的后端，需要和Java客户端通信。

**Comment by davyxu** [comment]
当然可以啊，说明里有封包格式，java那边和封包对上就可以通信

**Comment by bwangel23** [comment]
OK，谢谢。

**Comment by ihxzihxz** [comment]
> `	queue := cellnet.NewEventQueue()

	p := socket.NewConnector(queue)
	p.SetName("client.async")
	p.Start("127.0.0.1:9201")`

不用这些，就用纯go的
`  conn, err := net.Dial("tcp", "127.0.0.1:10000")`

**Comment by davyxu** [comment]
有第三方库你就直接用就是了嘛，如果需要自己解析，根据封包解就是了

**Comment by ihxzihxz** [comment]
不是，是我的客户端和上面那位一样，是app和单片机上来的数据，没有golang环境。不能用go做客户端

**Comment by davyxu** [comment]
那就根据封包和session里的代码分析下就是了
其他网络库或者协议都是这样做的
如果觉得麻烦，就用http吧
