### ISSUE TITLE
 .\RunAllTest.bat 和 运行 chat示例都报错

### ISSUE THREAD

**Issue by graceleeman** [davyxu/cellnet#32]
![image](https://user-images.githubusercontent.com/7553286/37442600-389fe778-2842-11e8-86df-eb6fb3a9bb2a.png)

**Comment by davyxu** [comment]
每次都会么？

**Comment by graceleeman** [comment]
恩，是的

**Comment by davyxu** [comment]
我这边暂时没有这个问题

**Comment by graceleeman** [comment]
我是刚刚新下的代码。
难到跟环境有关？我是在windows下运行的。

**Comment by davyxu** [comment]
以前偶尔有碰到这样的情况，但是是偶发。 我也是在windows上

**Comment by graceleeman** [comment]
![image](https://user-images.githubusercontent.com/7553286/37445449-089e5472-2853-11e8-904d-9c173f29261b.png)
服务还是能起来的，就是一有客户端连就报错，用浏览器连也报错。

**Comment by davyxu** [comment]
v4和v3架构完全不一样，尽量看v4吧。。。
