### ISSUE TITLE
问题和建议

### ISSUE THREAD

**Issue by jonfoo86** [davyxu/cellnet#37]
1,问题
客户端socket 断了, 我知道是哪个socket 端了吗?
Send发消息是堵塞的吗? 如果我有几千个链接,发到后面不是要延迟好久?  然后ses 发东西的时候类似线程安全吗?
Peer 在客户端断开的时候, 发消息会宕机 , 这个还需要自己处理好多东西,  
2, 建议, 
感觉网络通信框架 和protobuf 还有其他的 协议要分开,没必要都支持了, 就做纯的网络框架,其他功能通过插件的方式实现
感觉golang 的特色 chan 用的很少, 总觉得不能发挥go 的优势

哈哈哈哈
很赞的设计

**Comment by davyxu** [comment]
1. Socket断了会收到SessionClosed消息
2. 所有接口都不会阻塞，全异步， 发送可以并发啊
3. 怎么宕机，报什么错？
4. 关于扩展，请看v4分支。我们项目里就有对不同连接采用不一样的封包格式
5. 网络库是拿来用的，不是拿来体现Go的chan特色的。照这么说，C++网络库就必须全程手动管理session生命期和内存分配才应该具有C++网络库特性？
6. chan的特性并不是所有人都懂，但基本的接口和函数调用，任何新手都会。

感谢你的关注和建议
