### ISSUE TITLE
回调地狱 Callback Hell

### ISSUE THREAD

**Issue by samuelyao314** [davyxu/cellnet#39]
cellnet 是回调模式。如果用cellnet 实现逻辑服务器，一般需要访问其他服务（例如 查询好友信息， 锁服务端等） 。 这样很容易掉入Callback Hell。 请问，实际的项目中，你是如何解决这个问题的？

**Comment by davyxu** [comment]
异步回调对应单线程模式。mmo等类型的游戏模式，更适合用单线程来编写。

如果有复杂的异步处理问题，可以用rpc将逻辑聚集。

如果愿意，cellnet完全可以按照同步阻塞来做，不使用队列就好。
