### ISSUE TITLE
StringHash not unique, may cause msgid same

### ISSUE THREAD

**Issue by muqian3288** [davyxu/cellnet#42]
这是测试代码
func TestStringHash(t *testing.T) {
	a:="msg_protos.PKT_S2C_Reconnection_World_Status"
	b:="msg_protos.ShipEquipFireReq"
	t.Logf("a:%d,b:%d",StringHash(a),StringHash(b))
}
这是结果
strhash_test.go:8: a:7809,b:7809
如此下来，StringHash会有重复，会导致file.go MsgID 重复。
希望能换个MsgID的实现方式

**Comment by davyxu** [comment]
hash本身会冲撞，冲撞的时候有两种解决方法：
1.加盐（salt） ： 在名字加前缀或者后缀再进行hash
2. 直接修改消息名，避免冲突

cellnet不生成消息id，所以加盐这个可以自己处理

**Comment by muqian3288** [comment]
感谢davyxu的回答。我已经用了合适的方法（文件index，message index，生成msgid），修正了我的项目。

这段代码，我确认是cellnet下的。
protoc-gen-msg，会自动生成msgid.
file.go 下有这段代码
func (self *msgModel) MsgID() int {
	return int(util.StringHash(self.FullName()))
}
会导致MsgID 的相同的隐患。

期望能有标注，或者修掉这个隐患。

**Comment by davyxu** [comment]
这个隐患无法消除，hash本身机制已经决定了，这不是cellnet修复下就能搞定的。
