### ISSUE TITLE
支持一下自定义listener 

### ISSUE THREAD

**Issue by laolaozhang** [davyxu/cellnet#45]
https://github.com/davyxu/cellnet/blob/85be6eb8192b6551848f2cbc1cb4bdfb12a234ff/peer/tcp/acceptor.go#L19

标准的库的net.Listener是很好，但是遇到CC攻击获取其他高并发的情况下就麻烦了
比如我想用用这个库 https://github.com/valyala/tcplisten
 
所以支持一下自定义Listener,

还有网络库怎么能少得了这个方便的东西：
`
func setMaxConn() error {
	var RLimit syscall.Rlimit
	err := syscall.Getrlimit(syscall.RLIMIT_NOFILE, &RLimit)
	if err != nil {
		return err
	}
	log.Info("get setrlimit success", zap.Uint64("cur", RLimit.Cur), zap.Uint64("max", RLimit.Max))
	RLimit.Cur = 800000
	RLimit.Max = 800000
	err = syscall.Setrlimit(syscall.RLIMIT_NOFILE, &RLimit)
	if err != nil {
		return err
	}
	err = syscall.Getrlimit(syscall.RLIMIT_NOFILE, &RLimit)
	if err != nil {
		return err
	}
	log.Info("set setrlimit success", zap.Uint64("cur", RLimit.Cur), zap.Uint64("max", RLimit.Max))
	return nil
}
`

**Comment by davyxu** [comment]
peer可以完全自定义的，有特殊需求可以定制peer并注册
