### ISSUE TITLE
支持自定义解封包

### ISSUE THREAD

**Issue by laolaozhang** [davyxu/cellnet#46]
https://github.com/davyxu/cellnet/blob/85be6eb8192b6551848f2cbc1cb4bdfb12a234ff/util/packet.go#L53

支持自定义解封包
或者
支持包里面带metadata

作用：分布式服务之间通信用

**Comment by davyxu** [comment]
peer只是定义的收包流程，整个processor都可以被自定义的， 只需要注册到系统就可以，参考procreg.go以及相应的引用代码就直到怎么定制流程了。util里的函数只是helper，有很强的定制需求可以用自己的。
