### ISSUE TITLE
封包长度有限制

### ISSUE THREAD

**Issue by lemss** [davyxu/cellnet#49]
@davyxu 你好，我在使用cellnet的时候，发现V5版本有默认封包长度限制，客户端发送的是完整封包（大约30K），而服务端收到的就大概只有10K左右，然后服务端就会报错，Session会断开再连接，具体错误提示如下，请问一下该如何解决？

[ERRO] tcppeer 2018/06/27 20:54:58 session closed, sesid: 2, err: msg not exists, '26479'
[DEBU] tcpproc 2018/06/27 20:54:58 #tcp.recv(server)@2 len: 0 SessionClosed | {}
[DEBU] tcpproc 2018/06/27 20:55:00 #tcp.recv(server)@3 len: 0 SessionAccepted | {}

PS：V4版本没这个问题。

**Comment by davyxu** [comment]
现在cellnet版本是v4,你说的是v3没问题吧？

1. 不建议发送大封包，万一碰到有路由器策略不一致，会导致你完全收不到封包或者掉包，超过MTU（1400~1500byte）应该自行逻辑拆包，cellnet底层不拆包。
2. 不知道你用的是cellnet自带的协议发送，还是自己有改过。v4的自带的处理器读取封包的地方在util/packet.go中，你可以对比看下。
