### ISSUE TITLE
cellnet 热更新

### ISSUE THREAD

**Issue by samuelyao314** [davyxu/cellnet#51]
请问， cellnet 是否有计划，实现热更新机制。例如类似  https://github.com/facebookgo/grace
这样的实现。以个人经验，在生产环境，这个特性是非常重要的。

**Comment by davyxu** [comment]
1. cellnet支持的都是长连接，没法做热更新。
2. 服务做成无状态设计，随时重启比热更新更简单和稳定。
3. go现有的机制无法实现热更新，plugin是废柴，官方都放弃了。

**Comment by samuelyao314** [comment]
那请问，你们线上每周更新版本，是通过停服实现吗？ 还有临时版本修改bug,  又是如何做的

**Comment by samuelyao314** [comment]
针对建议2： 服务是可以无状态。每次操作完把数据都回写数据库。但问题是，你如果没有在框架层支持。你没法直接kill 重启啊。因为实际环境里肯定有用户请求正在被处理

**Comment by davyxu** [comment]
请加群527430600讨论，勿把issue当聊天大厅
