### ISSUE TITLE
tcp发送：发生“发送错误”时，error 没有处理

### ISSUE THREAD

**Issue by Jamlee** [davyxu/cellnet#58]
https://github.com/davyxu/cellnet/blob/ebba2f27eee1d09b388c8128fe094ba75370494e/proc/tcp/transmitter.go#L57

这里的 err 忽略了，当我没有注册消息类型时，调试了蛮久。后来发现这个错误没有 log 出来

**Comment by davyxu** [comment]
你的版本很老了吧

**Comment by Jamlee** [comment]
是 master 呀 ！！！

**Comment by Jamlee** [comment]
因为这个 error 没有被打印，感觉需要处理下不，打个 error log 提示一下 ？
