### ISSUE TITLE
目前master的example websocket 無作用

### ISSUE THREAD

**Issue by laota** [davyxu/cellnet#59]
依照index.html發送封包
server無法解析

[DEBU] websocket_server 2018/11/15 10:17:58 session closed:  2
[DEBU] gorillawsproc 2018/11/15 10:17:58 #ws.recv(server)@3 len: 0 SessionAccepted | {}
[DEBU] websocket_server 2018/11/15 10:17:58 server accepted
[DEBU] gorillawsproc 2018/11/15 10:17:58 #ws.recv(server)@3 len: 0  |

換回8月中抓的版本可正常運行

**Comment by davyxu** [comment]
已经添加二进制例子
