### ISSUE TITLE
【错误】lineraPipe 没有友好的退出

### ISSUE THREAD

**Issue by samuelyao314** [davyxu/cellnet#6]
func (self *lineraPipe) Stop(result int) {
    self.exitSignal <- result
}
func (self *lineraPipe) Wait() int {
    return <-self.exitSignal
}

Stop 执行后，并没有友好地停止之前的读取 datachan 循环。

**Comment by samuelyao314** [comment]
读完 datachan 后再退出，是否更好点？

**Comment by davyxu** [comment]
这块后期会处理
