### ISSUE TITLE
缺少peer_websocket.go

### ISSUE THREAD

**Issue by Rick82** [davyxu/cellnet#62]
您好，克隆下来有peer_tcp.go,但找不到 peer_websocket.go，目前比较常跟client连接的是websocket
可否补上?

**Comment by davyxu** [comment]
我从来没写过peer_tcp.go这个文件

这是连接端
https://github.com/davyxu/cellnet/blob/master/peer/gorillaws/connector.go

**Comment by RickSCho** [comment]
谢谢回复，我需要的是websocket connector接口，目前看来没有这接口，好用来取得session

**Comment by davyxu** [comment]
kan tests里的测试用例，搞懂怎么用

**Comment by RickSCho** [comment]
謝謝回復 已解決
