### ISSUE TITLE
RPC 消息导致主循环goroutinue挂起

### ISSUE THREAD

**Issue by samuelyao314** [davyxu/cellnet#66]
例子 client_rpc_async.go 里， 客户端收到RPC 回包， 因为   proc.BindProcessorHandler(p, "tcp.ltv", rv.EventCallback())。  所以主循环会被触发 rv.EventCallback() 返回的结果。  这是一个匿名函数

// syncrecv.go
	self.callback = func(ev cellnet.Event) {
		self.evChan <- ev
	}

因为一直没有消费者。queue绑定的主循环协程会被挂起。  我的结论是：在异步的RPC模式下，客户端已经在 MsgHooker ， 对RemoteCallACK进行了处理。  接下来 bundle.SetCallback 这里的回调函数不应该再被触发。

**Comment by davyxu** [comment]
SyncReceiver的本意,就是用来只等待某个消息而设计的. 这种模式下, 消息处理流程变成同步处理, 所以不会出现既要处理同步的SyncReceiver,还有异步消息需要处理的情况.

SyncReceiver只适用于一些特殊的使用情况, 如果有异步处理的需求, 则不应该使用SyncReceiver. 或者单独为SyncReceiver开启一个队列
