### ISSUE TITLE
树莓派下运行chat例子程序报错, segmentation violation

### ISSUE THREAD

**Issue by kindevil** [davyxu/cellnet#72]
pi@raspberrypi:~/go/src/github.com/davyxu/cellnet/examples/chat/server$ go run main.go 
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12b60]

    goroutine 1 [running]:
    runtime/internal/atomic.goLoad64(0x18d0224, 0x5f2390, 0x2ba608)
	    /opt/go/src/runtime/internal/atomic/atomic_arm.go:127 +0x1c
    github.com/davyxu/cellnet/peer.(*CoreRunningTag).IsRunning(...)
	    /home/pi/go/src/github.com/davyxu/cellnet/peer/runningtag.go:20
    github.com/davyxu/cellnet/peer/tcp.(*tcpAcceptor).Start(0x18d01e0, 0x18d01e0, 0x33cc04)
	    /home/pi/go/src/github.com/davyxu/cellnet/peer/tcp/acceptor.go:43 +0x3c
    main.main()
	    /home/pi/go/src/github.com/davyxu/cellnet/examples/chat/server/main.go:57 +0x174
    exit status 2

**Comment by davyxu** [comment]
这是go底层和arm兼容性造成的

**Comment by kindevil** [comment]
好吧，那就没办法了。。
