### ISSUE TITLE
httppeer 有bug

### ISSUE THREAD

**Issue by cd711** [davyxu/cellnet#73]
httpper的acceptor

```
        // 处理消息及页面下发
        self.ProcEvent(&cellnet.RecvMsgEvent{Ses: ses, Msg: msg})
	if ses.err != nil {
		err = ses.err
		goto OnError
	}
	if ses.respond {
		return
	}
```
因为ProcEvent是异步调用 导致 if ses.respond 判断时还没有执行逻辑代码.
然后这个判断后面的代码继续执行,可能返回404

**Comment by davyxu** [comment]
http的peer不要使用队列, newPeer那queue传nil

**Comment by cd711** [comment]
http的send必须用MessageRespond包装消息是吧?
另外 RegisterHttpMeta的ResponseType似乎有点小问题
既,我多个请求用相同回复时, RegisterHttpMeta不能注册相同的ResponseType

但是这里的ResponseType似乎又用不到.能否提供完整点的httppeer 例子
我看http_test里的是自己处理请求

**Comment by davyxu** [comment]
1. http的send必须用MessageRespond包装消息是吧?
是的

2. RegisterHttpMeta很快要废除了, 不要使用

3. http_test就是相对可用的例子.如果要大规模使用http, 请使用gin开源库

**Comment by cd711** [comment]
> * http的send必须用MessageRespond包装消息是吧?
>   是的
> * RegisterHttpMeta很快要废除了, 不要使用
> * http_test就是相对可用的例子.如果要大规模使用http, 请使用gin开源库

好的，非常感谢，，看来还是传统方式来做http比较合适
