### ISSUE TITLE
msgcodec.go 中的 EncodeMessage 函数, 后两个 return 没有返回值?

### ISSUE THREAD

**Issue by a674709300** [davyxu/cellnet#82]
今天读源码的时候忽然发现的,请问这是漏了吗?

**Comment by davyxu** [comment]
去看go的返回值一章, 这是基本语法

**Comment by a674709300** [comment]
啊,抱歉,犯低级错误了. 
还是没习惯go的语法, 只记得的通过参数的返回方式了,一下没绕过弯来,go的返回值可以有名字.
没注意把这个是返回值声明.
