### ISSUE TITLE
是否支持TLS加密

### ISSUE THREAD

**Issue by KeeeeiZ** [davyxu/cellnet#83]
我被cellnet强大的功能所吸引,所以希望可以使用它作为我的网络架构组件.  
目前正在TCP与websocket之间进行选择,由于一些原因,我希望我的网络服务器和客户端可以支持tls加密.  
如果使用TCP的话,可能我需要自定义一个Processor,并将listener改为tls,而不是net  
如果使用websocket的话,由于cellnet也对gorilla进行了封装,目前我没有找到合适的方法来应用https与wss来建立tls加密的链接.  

想请教一下项目的维护人员,有没有推荐的方案来帮助我实现tls加密的连接?

**Comment by davyxu** [comment]
ws的封装只是一种实现方式, 有TLS需求时, 可以在现有基础上自行调整

**Comment by KeeeeiZ** [comment]
是指不采用gorrilaws,换为自定义的封装吗?
作为项目作者,您觉得修改tcp的processor和调整ws封装哪一种更易于维护和修改呢?
因为我看cellnet的源码中如果想要修改tcp的listener,似乎只需要非常少量的修改即可(可能是我对项目不了解的错误判断).

**Comment by davyxu** [comment]
作为项目作者,您觉得修改tcp的processor和调整ws封装哪一种更易于维护和修改呢?
优先定制自己的processor, 实在不行, 再定制自己的peer

**Comment by srlemon** [comment]
// 侦听在18802端口
	p := peer.NewGenericPeer("gorillaws.Acceptor", "server", TestAddress, queue)
	p.(cellnet.WSAcceptor).SetHttps("","")

**Comment by KeeeeiZ** [comment]
> // 侦听在18802端口
> p := peer.NewGenericPeer("gorillaws.Acceptor", "server", TestAddress, queue)
> p.(cellnet.WSAcceptor).SetHttps("","")

非常感谢您的回复，我测试了这两行代码，但是报错提示
```
gorillaws 2019/12/06 11:48:55 #ws.connect failed(client) websocket: bad handshake
```
我执行的环境就是cellnet的examlple中的websocket。
我对client了做了同样的处理：
```go
p := peer.NewGenericPeer("gorillaws.Connector", "client", TestAddress, queue).(cellnet.WSConnector)
```
请问我是忽略了哪个环节吗？

**Comment by srlemon** [comment]
连接地址要用wss

**Comment by KeeeeiZ** [comment]
> 连接地址要用wss

地址换成wss之后解决了，非常感谢！
