### ISSUE TITLE
http服务绑定eventQueque会导致 404 错误。

### ISSUE THREAD

**Issue by 121351047** [davyxu/cellnet#87]

**Comment by davyxu** [comment]
http是并发处理, 不能绑定队列

**Comment by davyxu** [comment]
http是并发处理, 不能绑定队列

**Comment by 121351047** [comment]
明白了。那怎么和cellnet的 eventQueque 协调执行啊？比如cellmesh的游戏框架的 增加一个处理http请求的服务 ，这种情况不就变成了 主游戏逻辑运行在一个线程，http服务器运行在另一个线程了吗？我刚接触go语言，可能有说的不对的地方，请多指教。

**Comment by davyxu** [comment]
http接收和game不同进程rpc阻塞等待拉取数据后再做http返回, 同进程自己处理一个类似rpc的阻塞等待数据过程

**Comment by 121351047** [comment]
明白了 谢谢
