### ISSUE TITLE
在SendLTVPacket里面每次发送都创建一个同样大小的pkt

### ISSUE THREAD

**Issue by crossci** [davyxu/cellnet#97]
在SendLTVPacket里面每次发送都创建一个同样大小的pkt，我想每个连接上都提前创建一个大小合适的buff，这样每次发送都复用这个slice，我不确定writeFull是否会复用我自己创建发buff

**Comment by crossci** [comment]
这个问题的关键在于ioutil里面的WriteFull执行结束之后writer是否还会有引用指向参数buf，如果有的话，那每次发送就必须创建一个pkt

**Comment by davyxu** [comment]
go有逃逸检测的

**Comment by crossci** [comment]
pkt会逃逸到堆上面吗

**Comment by davyxu** [comment]
自己查下逃逸检测, 你按我原版设计代码写就好了, 不是每个地方都要用内存池
1. 不是每个内存分配都是走堆, 也可能是栈
2. Go的GC足够快
3. 内存池带来的问题远比gc带来的问题多的多

**Comment by crossci** [comment]
好的 明白 谢谢
