### ISSUE TITLE
有没有网关的实现列子

### ISSUE THREAD

**Issue by tangjiemian** [davyxu/cellnet#99]
有没有网关的实现列子

**Comment by davyxu** [comment]
自己根据需要实现

**Comment by tangjiemian** [comment]
web程序员，对游戏网关这种实现没有经验。想找一个demo参考学习




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Davy ***@***.***&gt;; 
发送时间: 2021年6月9日(星期三) 下午2:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [davyxu/cellnet] 有没有网关的实现列子 (#99)





 
自己根据需要实现

**Comment by davyxu** [comment]
https://gitee.com/chen_junji/YouYouFramework
一搜一大把, 语言不是事, 参考原理就是了

**Comment by tangjiemian** [comment]
cellnet网关层想接入tcp,websocket多种协议，怎么破
